apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-service
  namespace: jenkins-app
  labels:
    app: jenkins-app
spec:
  selector:
    app: jenkins-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080

